CREATE OR REPLACE TABLE {catalog_name}.gold_tp.tp_cntrt_lkp (
  cntrt_id BIGINT,
  cntrt_code VARCHAR(30),
  cntrt_name VARCHAR(200),
  cntrt_sttus_id SMALLINT,
  cntrt_sttus_name VARCHAR(200),
  data_tier VARCHAR(6),
  srce_sys_id SMALLINT,
  srce_sys_name VARCHAR(200),
  vendr_id SMALLINT,
  vendr_name VARCHAR(200),
  cntry_id VARCHAR(3),
  cntry_name VARCHAR(100),
  categ_id VARCHAR(3),
  categ_name VARCHAR(100),
  time_perd_type_code VARCHAR(4),
  crncy_id VARCHAR(3),
  wkf_job_id BIGINT,
  file_formt VARCHAR(10),
  file_patrn VARCHAR(200),
  mastr_valdn_ind CHAR(1),
  excl_paral_ind CHAR(1),
  auto_apprv_ind CHAR(1),
  retn_perd SMALLINT,
  start_date DATE,
  end_date DATE,
  mkt_grp_id SMALLINT,
  mkt_top_node_skid BIGINT,
  mkt_top_node_name VARCHAR(200),
  fct_avail_ind STRING,
  time_exprn_id SMALLINT,
  prmtn_ind CHAR(1),
  secure_group_key BIGINT)
USING delta
LOCATION 'abfss://tp-publish-data@{storage_name}.dfs.core.windows.net/TP_CNTRT_LKP'
TBLPROPERTIES (
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.allowColumnDefaults' = 'supported',
  'delta.feature.deletionVectors' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')
