CREATE OR REPLACE TABLE {catalog_name}.internal_tp.tp_mkt_skid_seq (
  mkt_skid BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000001 INCREMENT BY 1),
  run_id BIGINT,
  key STRING)
USING delta
TBLPROPERTIES (
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.identityColumns' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')
