CREATE OR REPLACE TABLE {catalog_name}.internal_tp.tp_mkt_sdim (
  mkt_skid BIGINT NOT NULL,
  extrn_mkt_id STRING,
  run_id BIGINT NOT NULL,
  srce_sys_id SMALLINT NOT NULL,
  cntrt_id BIGINT NOT NULL,
  mkt_name STRING,
  mkt_desc STRING,
  mkt_lvl_id SMALLINT,
  mkt_lvl_name STRING,
  mkt_grp_id SMALLINT,
  mkt_grp_name STRING,
  mkt_brkdw_type STRING,
  mkt_brkdw_name STRING,
  regn_id VARCHAR(6),
  regn_name VARCHAR(200),
  sub_regn_id VARCHAR(6),
  sub_regn_name VARCHAR(200),
  cntry_hub_id VARCHAR(10),
  cntry_hub_name VARCHAR(200),
  iso_cntry_code VARCHAR(2),
  cntry_name VARCHAR(200),
  iso_crncy_code VARCHAR(15),
  key_acct_name STRING,
  cust_name STRING,
  retl_bannr_name STRING,
  geo_name STRING,
  indus_class_name STRING,
  div_whse_name STRING,
  trade_chanl_name STRING,
  addr_name STRING,
  postl_code STRING,
  city_name STRING,
  lngtd_val DECIMAL(38,10),
  lttd_val DECIMAL(38,10),
  vendr_mkt_name STRING,
  store_num STRING,
  store_name STRING,
  ownr_name STRING,
  area_code STRING,
  st_code STRING,
  store_sttus_code STRING,
  beer_ind STRING,
  wine_ind STRING,
  liqr_ind STRING,
  phcy_ind STRING,
  gasln_ind STRING,
  vendr_store_code STRING,
  vendr_trade_chanl_code STRING,
  vendr_scan_mkt_code STRING,
  vendr_scan_mkt_name STRING,
  vendr_size_code STRING,
  fips_cnty_code STRING,
  fips_st_code STRING,
  dma_code STRING,
  dma_name STRING,
  mgb_area_code STRING,
  mgb_area_name STRING,
  mgb_regn_name STRING,
  msa_code STRING,
  msa_name STRING,
  vendr_chanl_code STRING,
  part_srce_sys_id SMALLINT)
USING delta
PARTITIONED BY (part_srce_sys_id)
LOCATION 'abfss://tp-publish-data@{storage_name}.dfs.core.windows.net/INTERNAL/TP_MKT_SDIM'
TBLPROPERTIES (
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.allowColumnDefaults' = 'supported',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')
